# Generated by Django 3.1.7 on 2021-12-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subject_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedteacher',
            name='id',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
