# Generated by Django 3.1.7 on 2021-12-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_assignedteacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedteacher',
            name='course_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='assignedteacher',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
