# Generated by Django 3.1.7 on 2021-12-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211208_1835'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignedteacher',
            unique_together={('student_dept', 'course_code')},
        ),
    ]
