# Generated by Django 3.1.7 on 2021-12-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211212_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(default='NotRatedYet', max_length=20),
        ),
    ]
